import type { Summary, JobAnalysis } from '@/types/summary';

export function summaryToMarkdown(summary: Summary): string {
  const lines: string[] = [];

  lines.push(`# ${summary.metadata.title}`);
  lines.push('');
  lines.push(`> ${summary.metadata.url}`);
  lines.push('');
  lines.push(
    `**Category:** ${summary.metadata.category} | ` +
    `**Sentiment:** ${summary.metadata.sentiment} | ` +
    `**Reading Time:** ${summary.metadata.readingTime} | ` +
    `**Complexity:** ${summary.metadata.complexity}`
  );
  lines.push('');

  lines.push('## TL;DR');
  lines.push('');
  lines.push(summary.tldr);
  lines.push('');

  lines.push('## Key Takeaways');
  lines.push('');
  for (const takeaway of summary.keyTakeaways) {
    lines.push(`- ${takeaway}`);
  }
  lines.push('');

  if (summary.importantFacts.length > 0) {
    lines.push('## Important Facts');
    lines.push('');
    for (const fact of summary.importantFacts) {
      lines.push(`- ${fact}`);
    }
    lines.push('');
  }

  if (summary.actionItems.length > 0) {
    lines.push('## Action Items');
    lines.push('');
    for (const item of summary.actionItems) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (summary.technologies.length > 0) {
    lines.push('## Technologies');
    lines.push('');
    lines.push(summary.technologies.join(', '));
    lines.push('');
  }

  if (summary.tags.length > 0) {
    lines.push('## Tags');
    lines.push('');
    lines.push(summary.tags.map((tag) => `\`${tag}\``).join(' '));
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Agentic AI Browser Assistant*');

  return lines.join('\n');
}

export function jobToMarkdown(job: JobAnalysis): string {
  const lines: string[] = [];

  lines.push(`# ${job.role}`);
  lines.push('');
  lines.push(`**Company:** ${job.company}`);
  lines.push(`**Location:** ${job.location}`);
  lines.push(`**Employment Type:** ${job.employmentType}`);
  lines.push(`**Experience:** ${job.experience}`);
  lines.push(`**Salary:** ${job.salary}`);
  lines.push('');

  lines.push('## TL;DR');
  lines.push('');
  lines.push(job.tldr);
  lines.push('');

  if (job.requiredSkills.length > 0) {
    lines.push('## Required Skills');
    lines.push('');
    for (const skill of job.requiredSkills) {
      lines.push(`- ${skill}`);
    }
    lines.push('');
  }

  if (job.preferredSkills.length > 0) {
    lines.push('## Preferred Skills');
    lines.push('');
    for (const skill of job.preferredSkills) {
      lines.push(`- ${skill}`);
    }
    lines.push('');
  }

  if (job.responsibilities.length > 0) {
    lines.push('## Responsibilities');
    lines.push('');
    for (const responsibility of job.responsibilities) {
      lines.push(`- ${responsibility}`);
    }
    lines.push('');
  }

  if (job.resumeKeywords.length > 0) {
    lines.push('## Resume Keywords');
    lines.push('');
    lines.push(job.resumeKeywords.join(', '));
    lines.push('');
  }

  if (job.interviewTopics.length > 0) {
    lines.push('## Interview Topics');
    lines.push('');
    for (const topic of job.interviewTopics) {
      lines.push(`- ${topic}`);
    }
    lines.push('');
  }

  lines.push(`## Difficulty Score`);
  lines.push('');
  lines.push(`${job.difficultyScore} / 10`);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Agentic AI Browser Assistant*');

  return lines.join('\n');
}

export function summaryToPlainText(summary: Summary): string {
  const lines: string[] = [];

  lines.push(summary.metadata.title);
  lines.push(summary.metadata.url);
  lines.push('');
  lines.push(
    `Category: ${summary.metadata.category} | ` +
    `Sentiment: ${summary.metadata.sentiment} | ` +
    `Reading Time: ${summary.metadata.readingTime} | ` +
    `Complexity: ${summary.metadata.complexity}`
  );
  lines.push('');

  lines.push('TL;DR');
  lines.push(summary.tldr);
  lines.push('');

  lines.push('Key Takeaways');
  for (const takeaway of summary.keyTakeaways) {
    lines.push(`  - ${takeaway}`);
  }
  lines.push('');

  if (summary.importantFacts.length > 0) {
    lines.push('Important Facts');
    for (const fact of summary.importantFacts) {
      lines.push(`  - ${fact}`);
    }
    lines.push('');
  }

  if (summary.actionItems.length > 0) {
    lines.push('Action Items');
    for (const item of summary.actionItems) {
      lines.push(`  - ${item}`);
    }
    lines.push('');
  }

  if (summary.technologies.length > 0) {
    lines.push('Technologies');
    lines.push(summary.technologies.join(', '));
    lines.push('');
  }

  if (summary.tags.length > 0) {
    lines.push('Tags');
    lines.push(summary.tags.join(', '));
    lines.push('');
  }

  lines.push('Generated by Agentic AI Browser Assistant');

  return lines.join('\n');
}

export function downloadAsFile(
  content: string,
  filename: string,
  type: string = 'text/markdown'
): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function summaryToEmailBody(summary: Summary): string {
  const lines: string[] = [];

  lines.push(`Summary: ${summary.metadata.title}`);
  lines.push('');
  lines.push(`Source: ${summary.metadata.url}`);
  lines.push('');
  lines.push('TL;DR');
  lines.push(summary.tldr);
  lines.push('');
  lines.push('Key Takeaways');
  for (const takeaway of summary.keyTakeaways) {
    lines.push(`  - ${takeaway}`);
  }
  lines.push('');
  lines.push('--');
  lines.push('Shared via Agentic AI Browser Assistant');

  return lines.join('\n');
}

export function openEmailWithSummary(summary: Summary): void {
  const subject = encodeURIComponent(`Summary: ${summary.metadata.title}`);
  const body = encodeURIComponent(summaryToEmailBody(summary));
  const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;
  window.open(mailtoUrl);
}
